clean:
	rm -rf lda_output

hdfs-clean:
	hdfs dfs -rm -r -f /game_reviews/*/output
	hdfs dfs -rm -r -f /game_reviews/*/vector
	hdfs dfs -rm -r -f /game_reviews/*/out
	hdfs dfs -rm -r -f /game_reviews/*/temp
	hdfs dfs -rm -r -f /game_reviews/*/lda
	hdfs dfs -rm -r -f /game_reviews/*/lda-topics
	hdfs dfs -rm -r -f /game_reviews/*/sparse_vectors_cvb	
